/* Fazer uma seleção de cliente trazendo o código das cidades, sem repetir. */

SELECT DISTINCT C.IDCLIENTE, C.NOME, C.DTNASCIMENTO, C.STATUS, C.RUA, C.NUMERO, C.BAIRRO, C.COMPLEMENTO, C.IDCIDADE, CID.NOME AS CIDADE_NOME
FROM CLIENTE C
JOIN CIDADE CID ON C.IDCIDADE = CID.IDCIDADE;
